spring:
  config:
    import: optional:file:.env[.properties]

  messages:
    basename: messages-validation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:mysql://localhost:3306/minimalest?serverTimezone=Asia/Seoul}
  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  cloud:
    aws:
      region:
        static: ${AWS_REGION:ap-northeast-2}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      ses:
        credentials:
          access-key: ${AWS_SES_ACCESS_KEY}
          secret-key: ${AWS_SES_SECRET_ACCESS_KEY}

auth:
  jwt:
    issuer: ${AUTH_JWT_ISSUER:minimalest.kr}
    secret-key: ${AUTH_JWT_SECRET_KEY:1234567890abcdefghijk!@#$%^&*()_+}
    access-validity-in-seconds: ${AUTH_JWT_ACCESS_VALIDITY_IN_SECONDS:3600} # 1시간
    refresh-validity-in-seconds: ${AUTH_JWT_REFRESH_VALIDITY_IN_SECONDS:604800}

mail:
  from-email: ${MAIL_FROM_EMAIL:noreply@minimalest.kr}
  verification:
    link-base-url: ${MAIL_VERIFICATION_LINK_BASE_URL:http://localhost:8080}
    link-path: ${MAIL_VERIFICATION_LINK_PATH:/api/v1/auth/verify}
    subject: ${MAIL_VERIFICATION_SUBJECT:Minimalest 이메일 인증}
    token-validity-hours: ${MAIL_VERIFICATION_TOKEN_VALIDITY_HOURS:24}

redis:
  email-token-prefix: ${REDIS_EMAIL_TOKEN_PREFIX:email:verification:}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

