spring:
  config:
    import: optional:file:.env[.properties]

  messages:
    basename: messages-validation
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: ${DB_URL:jdbc:mysql://localhost:3306/minimalest?serverTimezone=Asia/Seoul}
  jpa:
    hibernate:
      ddl-auto: update

  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
      s3:
        bucket: ${AWS_S3_BUCKET_NAME}
      region:
        static: ${AWS_S3_REGION:ap-northeast-2}

auth:
  jwt:
    issuer: ${AUTH_JWT_ISSUER:minimalest.kr}
    secret-key: ${AUTH_JWT_SECRET_KEY:1234567890abcdefghijk!@#$%^&*()_+}
    access-validity-in-seconds: ${AUTH_JWT_ACCESS_VALIDITY_IN_SECONDS:3600} # 1시간
    refresh-validity-in-seconds: ${AUTH_JWT_REFRESH_VALIDITY_IN_SECONDS:604800}

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
